### ISSUE TITLE
Game / Team Chat Doesn't Play Well With Some Chat Plugins

### ISSUE THREAD

**Issue by Parsonswy** [ScreamingSandals/BedWars#120]
#### Describe the bug
We run BedWars on a minigames server in our network. We use a plugin called MultiChat to provide global chat. Whenever someone is playing BedWars and uses teamchat, their messages are hidden from anyone on the minigames server (expected), but get forwarded on by MultiChat so they appear on every other server in the network.

I'm reporting as a bug here because the current BedWars teamchat implementation will cause issues with any plugin that listens to `PlayerChatEvent`s. Since the chat event is not cancelled, [the recipient list is only modified](https://github.com/ScreamingSandals/BedWars/blob/master/plugin/src/main/java/org/screamingsandals/bedwars/listener/PlayerListener.java#L862), other plugins have no other way of knowing that they should ignore the teamchat message. I think the more widely compatible way to handle this would be to cancel the chat event and loop over all player's that need to see the message, running `Player.sendMessage()`.

#### Server and plugin version
Spigot version: 1.15.2
BedWars version: 0.2.5

#### Installed plugins on server (can be obtained by `/pl`)
```
BasicAntiCheat, BedWars, BungeeTabListPlus, CoreProtect, Essentials, EssentialsSpawn, HolographicDisplays, LuckPerms, MobArena, MultiChatSpigot, Multiverse-Core, Skript, skript-mirror*, SQLibrary*, SuperbVote, Vault, VoidGenerator, Votifier, WorldEdit, WorldGuard, XXS
```
#### Console log
N/A

#### Configuration (of config.yml and shop.yml)
Related Chat Configuration
```YAML
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '@a'
  team-chat-prefix: '@t'
  all-chat: '[ALL] '
  team-chat: '[TEAM] '
  death-chat: '[DEATH] '
  separate-chat:
    lobby: true
    game: true
```
#### If there are problem with only one game, paste here config of this game
Happens in all games.
