### ISSUE TITLE
Can't open villager shop in recent Paper builds.

### ISSUE THREAD

**Issue by xCustomWorld** [ScreamingSandals/BedWars#125]
#### Describe the bug
Cannot open a villager shop.

#### Server and plugin version
Spigot version: paper-143 (1.15.2)
BedWars version: 0.2.5

#### Installed plugins on server (can be obtained by `/pl`)
Prefer to stay anonymous. I'm pretty sure this is just caused by changes in recent Paper builds - many plugins had to update because they broke in these builds. I want to stay up to date with these builds as they provide important bug fixes. And the fact that it worked just fine a couple builds back and I haven't added any new plugins is proof it's not plugin incompatibility in my opinion. 

#### Console log
`
[Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to BedWars v0.2.5 java.lang.NullPointerException: null 	at org.screamingsandals.bedwars.lib.sgui.GuiHolder.repaint(GuiHolder.java:85) ~[?:?] 	at org.screamingsandals.bedwars.lib.sgui.GuiHolder.<init>(GuiHolder.java:40) ~[?:?] 	at org.screamingsandals.bedwars.lib.sgui.SimpleGuiFormat.openForPlayer(SimpleGuiFormat.java:1107) ~[?:?] 	at org.screamingsandals.bedwars.inventories.ShopInventory.show(ShopInventory.java:157) ~[?:?] 	at org.screamingsandals.bedwars.Main.openStore(Main.java:207) ~[?:?] 	at org.screamingsandals.bedwars.listener.VillagerListener.onVillagerInteract(VillagerListener.java:35) ~[?:?] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1254.execute(Unknown Source) ~[?:?] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-143] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-143] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202] [09:37:40] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to BedWars v0.2.5 java.lang.NullPointerException: null 	at org.screamingsandals.bedwars.lib.sgui.GuiHolder.repaint(GuiHolder.java:85) ~[?:?] 	at org.screamingsandals.bedwars.lib.sgui.GuiHolder.<init>(GuiHolder.java:40) ~[?:?] 	at org.screamingsandals.bedwars.lib.sgui.SimpleGuiFormat.openForPlayer(SimpleGuiFormat.java:1107) ~[?:?] 	at org.screamingsandals.bedwars.inventories.ShopInventory.show(ShopInventory.java:157) ~[?:?] 	at org.screamingsandals.bedwars.Main.openStore(Main.java:207) ~[?:?] 	at org.screamingsandals.bedwars.listener.VillagerListener.onVillagerInteract(VillagerListener.java:35) ~[?:?] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1254.execute(Unknown Source) ~[?:?] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-143] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-143] 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-143] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
`

#### Configuration (of config.yml and shop.yml)
config.yml:
```
locale: en
debug: false
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 0
spawner-holo-height: 0.1
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: true
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: false
player-respawn-items: false
gived-game-start-items: []
gived-player-respawn-items: []
disable-hunger: true
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allow-spectator-join: false
disable-server-messagef:
  player-join: false
  player-leave: false
respawn-cooldown:
  enabled: true
  time: 5
stop-team-spawners-on-die: false
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
farmBlocks:
  enable: false
  blocks: []
scoreboard:
  enable: true
  title: §a%game%§r - %time%
  bedLost: §c✘
  bedExists: §a✔
  teamTitle: '§8[§r%bed%§8]§r %color%%team%'
title:
  fadeIn: 20
  stay: 60
  fadeOut: 10
items:
  jointeam: COMPASS
  leavegame: DARK_OAK_DOOR
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: false
  reward:
    kill: 5
    win: 20
resources:
  emerald:
    material: EMERALD
    color: GREEN
    name: Emerald
    interval: 30
    translate: resource_emerald
    spread: 2.0
  diamond:
    material: DIAMOND
    color: BLUE
    name: Diamond
    interval: 15
    translate: resource_diamond
    spread: 1.0
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Gold
    interval: 10
    translate: resource_gold
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: GRAY
    name: Iron
    interval: 5
    translate: resource_iron
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 10
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: true
    delay: 5
    break-time: 10
    distance: 1
    material: WHITE_STAINED_GLASS
  protection-wall:
    is-breakable: true
    delay: 20
    break-time: 0
    width: 5
    height: 4
    distance: 3
    material: BRICKS
  tnt-sheep:
    speed: 2.0
    follow-range: 20.0
    max-target-distance: 32
    explosion-time: 10
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 5
    delay: 30
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.45
    follow-range: 20
    health: 50
    name-format: '%teamcolor%%team%§7''s Golem'
    show-name: true
    delay: 0
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
tnt:
  auto-ignite: true
  explosion-time: 10
sounds:
  on_bed_destroyed: ENTITY_ENDER_DRAGON_GROWL
  on_countdown: UI_BUTTON_CLICK
  on_game_start: ENTITY_PLAYER_LEVELUP
  on_team_kill: ENTITY_PLAYER_LEVELUP
  on_player_kill: ENTITY_PLAYER_BIG_FALL
  on_item_buy: ENTITY_ITEM_PICKUP
  on_upgrade_buy: ENTITY_EXPERIENCE_ORB_PICKUP
  on_respawn_cooldown_wait: UI_BUTTON_CLICK
  on_respawn_cooldown_done: ENTITY_PLAYER_LEVELUP
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start:
    effects:
    - ==: Firework
      flicker: true
      trail: true
      colors:
      - &id002
        ==: Color
        RED: 0
        BLUE: 255
        GREEN: 47
      fade-colors:
      - *id002
      type: BALL
    power: 2
    type: Firework
  kill: {}
  teamkill:
    effects:
    - ==: Firework
      flicker: true
      trail: true
      colors:
      - &id003
        ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id003
      type: BALL
    power: 2
    type: Firework
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy:
    effects:
    - ==: Firework
      flicker: true
      trail: true
      colors:
      - &id004
        ==: Color
        RED: 0
        BLUE: 0
        GREEN: 0
      fade-colors:
      - *id004
      type: BALL
    power: 3
    type: Firework
  warppowdertick: {}
lobby-scoreboard:
  enabled: true
  title: §c§lBed§f§lWars
  content:
  - ' '
  - '§fMap: §2%arena%'
  - '§fPlayers: §2%players%§f/§2%maxplayers%'
  - ' '
  - §7Waiting...
  - ' '
statistics:
  enabled: true
  type: yaml
  show-on-game-end: true
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: localhost
  port: 3306
  db: databse
  user: root
  password: secret
  table-prefix: bw_
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: §e☼ §6Your §c§lBed§f§lWars§r§6 stats§e ☼
chat:
  override: true
  format: '%teamcolor%%name%§r: '
  separate-chat:
    lobby: false
    game: false
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '!'
  team-chat-prefix: '!t'
  all-chat: §c§l[Shout] §r
  team-chat: §a§l[Team Chat] §r
  death-chat: §4§l[DEATH] §r
rewards:
  enabled: true
  player-win:
  - /cmi money give {player} 100
  player-end-game:
  - /cmi money give {player} 10
  player-destroy-bed:
  - /cmi money give {player} 20
  player-kill:
  - /cmi money give {player} 10
lore:
  generate-automatically: true
  text:
  - '§ePrice:'
  - §6%price%§r §e%resource%§r
  - §r
  - '§aAmount:'
  - §e%amount%§6x
sign:
- §4§l[§c§lBed§f§lWars§4§l]
- '%arena%'
- '%status%'
- '%players%'
hotbar:
  selector: 0
  color: 4
  start: 7
  leave: 8
breakable:
  enabled: false
  asblacklist: false
  blocks: []
leaveshortcuts:
  enabled: false
  list:
  - leave
mainlobby:
  enabled: true
  location: -277.536551298209;74.0;278.61667843374045;357.83765;-1.0499254
  world: Hub
version: 2
disable-server-message:
  player-join: false
  player-leave: false

```
shop.yml:
```
--- 
data: 
  - 
    items: 
      - 
        price: "2 of iron"
        properties: applycolorbyteam
        stack: 
          enchants: 
            PROTECTION_ENVIRONMENTAL: 1
          type: LEATHER_HELMET
      - 
        price: "3 of iron"
        properties: applycolorbyteam
        stack: 
          enchants: 
            PROTECTION_ENVIRONMENTAL: 1
          type: LEATHER_LEGGINGS
      - 
        price: "1 of iron"
        properties: applycolorbyteam
        stack: 
          enchants: 
            PROTECTION_ENVIRONMENTAL: 1
          type: LEATHER_BOOTS
      - 
        price: "3 of gold"
        stack: 
          enchants: 
            PROTECTION_ENVIRONMENTAL: 1
          type: CHAINMAIL_CHESTPLATE
      - 
        price: "5 of gold"
        stack: 
          enchants: 
            PROTECTION_ENVIRONMENTAL: 2
          type: CHAINMAIL_CHESTPLATE
      - 
        price: "7 of gold"
        stack: 
          enchants: 
            PROTECTION_ENVIRONMENTAL: 3
          type: CHAINMAIL_CHESTPLATE
      - 
        price: "20 of iron"
        stack: 
          enchants: 
            PROTECTION_ENVIRONMENTAL: 2
          type: IRON_HELMET
    stack: "DIAMOND_CHESTPLATE;1;§a§lArmor;§eProtect yourself with armor! Click here."
  - 
    column: center
    items: 
      - 
        price: "2 of emerald"
        stack: 
          enchants: 
            KNOCKBACK: 1
          type: STICK
      - 
        price: "15 of iron"
        stack: 
          type: WOODEN_SWORD
      - 
        price: "25 of iron"
        stack: 
          type: STONE_SWORD
      - 
        price: "35 of iron"
        stack: 
          type: IRON_SWORD
      - 
        price: "35 of diamond"
        stack: 
          type: DIAMOND_SWORD
      - 
        price: "10 of emerald"
        stack: 
          display-name: "The Axe"
          enchants: 
            DAMAGE_ALL: 2
            DURABILITY: 3
            KNOCKBACK: 1
          type: DIAMOND_AXE
    stack: "DIAMOND_SWORD;1;§b§lSwords;§eClick here to get sword for attacking your enemies"
  - 
    column: right
    items: 
      - 
        price: "25 of iron"
        stack: 
          type: BOW
      - 
        price: "25 of gold"
        stack: 
          enchants: 
            ARROW_DAMAGE: 1
          type: BOW
      - 
        price: "32 of gold"
        stack: 
          enchants: 
            ARROW_DAMAGE: 2
          type: BOW
      - 
        price: "32 of diamond"
        stack: 
          enchants: 
            ARROW_FIRE: 1
          type: BOW
      - 
        price: "25 of emerald"
        stack: 
          enchants: 
            ARROW_FIRE: 1
            ARROW_KNOCKBACK: 1
          type: BOW
      - "ARROW for 1 of gold"
    stack: "BOW;1;§6§lBows;§6Prove yourself as a marksman with these wonderful bows"
  - 
    column: 2
    items: 
      - "COOKED_PORKCHOP;2 for 10 of iron"
      - "BREAD;10 for 32 of gold"
      - "GOLDEN_APPLE for 10 of diamond"
    row: 3
    stack: "COOKED_PORKCHOP;1;§cFood;§eAre you hungry? Get something to eat."
  - 
    column: 6
    items: 
      - 
        price: "30 of iron"
        stack: 
          meta: 
            ==: ItemMeta
            meta-type: POTION
            potion-type: healing
          type: POTION
      - 
        price: "25 of diamond"
        stack: 
          meta: 
            ==: ItemMeta
            meta-type: POTION
            potion-type: strong_healing
          type: POTION
      - 
        price: "32 of gold"
        stack: 
          meta: 
            ==: ItemMeta
            meta-type: POTION
            potion-type: swiftness
          type: POTION
      - 
        price: "10 of emerald"
        stack: 
          meta: 
            ==: ItemMeta
            meta-type: POTION
            potion-type: strength
          type: POTION
      - 
        price: "20 of emerald"
        stack: 
          meta: 
            ==: ItemMeta
            meta-type: POTION
            potion-type: regeneration
          type: POTION
    row: 3
    stack: 
      meta: 
        ==: ItemMeta
        display-name: §d§lDrinks
        lore: 
          - "§eNot enough? Use these potions and you'll feel better!"
        meta-type: POTION
        potion-type: strength
      type: POTION
  - 
    items: 
      - "CUT_SANDSTONE;3 for 1 of iron"
      - "END_STONE;3 for 5 of gold"
      - "IRON_BLOCK for 10 of iron"
      - "GLOWSTONE;5 for 15 of gold"
      - 
        price: "1 of diamond"
        properties: applycolorbyteam
        stack: GLASS
      - "OBSIDIAN for 5 of emerald"
    linebreak: before
    stack: "SANDSTONE;1;§6§lBlocks;§eGet to the others! Possible with blocks."
  - 
    column: center
    items: 
      - "CHEST for 10 of iron"
      - "ENDER_CHEST for 1 of emerald"
      - 
        price: "10 of emerald"
        properties: 
          - 
            delay: 5
            name: WarpPowder
        stack: 
          display-name: "§9Warp Powder"
          lore: 
            - "§eWhen using this powder you'll get"
            - "§eteleported to you spawn point within 5 seconds"
            - §r
            - "§c§lWarning: §cAny movement will stop the process"
          type: GUNPOWDER
      - 
        price: "8 of diamond"
        properties: 
          - 
            data: 
              - 
                sound: ENTITY_SHEEP_AMBIENT
              - 
                effect: 
                  ==: org.bukkit.potion.PotionEffect
                  ambient: true
                  amplifier: 2
                  duration: 100
                  effect: 15
                  has-icon: true
                  has-particles: true
              - 
                effect: 
                  ==: org.bukkit.potion.PotionEffect
                  ambient: true
                  amplifier: 2
                  duration: 100
                  effect: 18
                  has-icon: true
                  has-particles: true
              - 
                effect: 
                  ==: org.bukkit.potion.PotionEffect
                  ambient: true
                  amplifier: 2
                  duration: 100
                  effect: 2
                  has-icon: true
                  has-particles: true
            name: Trap
        stack: 
          display-name: §cTrap
          lore: 
            - "§eGet informed if an enemy steps on your trap"
            - "§eand your enemy won't be able to move properly."
          type: STRING
      - 
        price: "5 of emerald"
        properties: 
          - 
            name: MagnetShoes
            probability: 75
        stack: 
          display-name: §eMagnet-Shoes
          lore: 
            - "§eWear those shoes and have a 75%"
            - "§echance of getting no knockback!"
          type: IRON_BOOTS
      - 
        price: "5 of diamond"
        properties: Tracker
        stack: 
          display-name: §dTracker
          lore: 
            - "§eWanna know where your closest target is?"
            - "§eLet's try this out!"
          type: COMPASS
      - 
        price: "16 of diamond"
        properties: 
          - 
            delay: 5
            name: rescueplatform
        stack: 
          display-name: "§cRescue Platform"
          lore: 
            - "§eProtect yourself from falling into"
            - "§evoid with a Rescue Platform."
            - "§eThis is your last hope!"
            - "§r"
            - "§c§lWarning: §cYou'll take fall damage
            - "§cif you use" the platform too late!"
          type: BLAZE_ROD
      - 
        price: "16 of gold"
        properties: 
          - 
            delay: 5
            name: arrowblocker
        stack: 
          display-name: "§bArrow Blocker"
          lore: 
            - "§eBlock arrows that are coming"
            - "§efor you with black magic-"
            - "§a...I mean, with this item."
          type: ENDER_EYE
      - 
        price: "32 of gold"
        properties: 
          - 
            name: protectionwall
        stack: 
          display-name: "§cProtection Wall"
          lore: 
            - "§eInstantly builds a wall that"
            - "§ecan save your life!"
          type: BRICKS
      - 
        price: "30 of emerald"
        properties: 
          - 
            follow: 16.0
            name: Golem
            speed: 0.25
        stack: 
          display-name: §cGolem
          lore: 
            - "§eAn iron golem that will protect"
            - "§eyour team from the enemies."
          type: GHAST_SPAWN_EGG
      - 
        price: "25 of emerald"
        properties: TNTSheep
        stack: 
          display-name: "TNT Sheep"
          lore: 
            - "§eUse the TNT-Sheep! It will"
            - "§ewalk towards your closest enemy"
            - "§eand explode within 8 seconds!"
          type: SHEEP_SPAWN_EGG
    stack: "TNT;1;§e§lUseful Stuff;§eLooking for useful stuff? Here are some!"
  - 
    column: right
    items: 
      - 
        price: "5 of iron"
        stack: 
          enchants: 
            LOOT_BONUS_BLOCKS: 1
          type: IRON_PICKAXE
      - 
        price: "15 of iron"
        stack: 
          enchants: 
            LOOT_BONUS_BLOCKS: 2
          type: IRON_PICKAXE
      - 
        price: "20 of gold"
        stack: 
          enchants: 
            LOOT_BONUS_BLOCKS: 3
          type: IRON_PICKAXE
      - 
        price: "25 of diamond"
        stack: 
          enchants: 
            LOOT_BONUS_BLOCKS: 1
          type: DIAMOND_PICKAXE
    stack: "DIAMOND_PICKAXE;1;§b§lPickaxes;§eDestroy others blocks? Use these pickaxes."
```

I haven't made any changes to the shop.yml recently - before updating Paper, it worked fine.

#### If there are problem with only one game, paste here config of this game
No, it affects all areas.
