### ISSUE TITLE
Signs will always say that area is disabled when server (re)starts.

### ISSUE THREAD

**Issue by xCustomWorld** [ScreamingSandals/BedWars#126]
#### Describe the bug
Every time server restarts, all signs will say that the area is disabled even though they are enabled and can be joined by using commands. I think it's caused because signs may load before areas, which will result in signs thinking that these areas are disabled.

#### Server and plugin version
Spigot version: paper-143 (1.15.2)
BedWars version: 0.2.5

#### If there is a problem with only one game, paste here config of this game.
All areas are affected.

**Comment by iamceph** [comment]
Any console errors?

**Comment by Misat11** [comment]
And can you use the sign for join? Also have you some clearlagg or some other plugin that unloads chunks? When chunk is not loaded, plugin can't update signs.

**Comment by xCustomWorld** [comment]
No console errors, I do have a clear lag plugin. I can't use the signs to join.

**Comment by Misat11** [comment]
Have you these signs in file signs.yml? (if not, recreate the sign in game)

**Comment by xCustomWorld** [comment]
Yes, here is the `sign.yml` file:
```
sign:
- name: Two_Kingdoms
  location:
    ==: org.bukkit.Location
    world: Hub
    x: -278.0
    y: 75.0
    z: 282.0
    pitch: 0.0
    yaw: 0.0
- name: Neighborhood
  location:
    ==: org.bukkit.Location
    world: Hub
    x: -277.0
    y: 75.0
    z: 282.0
    pitch: 0.0
    yaw: 0.0
```
