### ISSUE TITLE
Stats not updating properly

### ISSUE THREAD

**Issue by Crush3rX** [ScreamingSandals/BedWars#151]
#### Describe the bug

1.  Stats displayed in the hologram are not updated on player join, only on server start.

2. Kills, deaths and score arent properly saved to databases. making 3 kills and 3 deaths ingame results in `1` showing in the database.

Bungee setup
- Lobby (with just the holo, no arenas)
- Gameserver 1
- Gamerserver 2

Empty database and stats show zero.

![afbeelding](https://user-images.githubusercontent.com/4728780/80796395-57f5aa00-8b9f-11ea-870a-b14fd39f7e8f.png)

Win a game and return to lobby. Made 3 kills and 3 deaths with both players.

![afbeelding](https://user-images.githubusercontent.com/4728780/80796612-ec600c80-8b9f-11ea-8d19-a16fbfe3c689.png)

Playing a match on gameserver 2 and letting the other player win, then back in lobby it shows this

![afbeelding](https://user-images.githubusercontent.com/4728780/80797162-6644c580-8ba1-11ea-8e2c-f89c501dd6b8.png)

Restarting lobby server (/stop) and results are like this:

![afbeelding](https://user-images.githubusercontent.com/4728780/80797454-2a5e3000-8ba2-11ea-9f5f-e39af25a536a.png)

Conclusion: Stats are only loaded on server start.

#### Server and plugin version
Spigot version: 1.15.2 Paper 226
BedWars version: 0.2.7 (latest release)

#### Installed plugins on server (can be obtained by `/pl`)
Lobby:
BedWars, BungeeTabListPlus, ChatControl, LuckPerms, ProtocolLib, Vault, WorldEdit

Gameservers:
BedWars, BungeeTabListPlus, ChatControl, LuckPerms, ProtocolLib, Vault, WorldEdit

#### Console log
Nothing related to this.

#### Configuration (of config.yml and shop.yml)
```
....
statistics:
  enabled: true
  type: database
  show-on-game-end: true
  bed-destroyed-kills: true
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: *
  port: 3306
  db: `bedwars`
  user: *
  password: *
  table-prefix: bw
....
```

#### If there are problem with only one game, paste here config of this game
Happends for all servers runnning this plugin.
