### ISSUE TITLE
NullPointerException on changeGame();

### ISSUE THREAD

**Issue by dustinfht** [ScreamingSandals/BedWars#220]
#### Describe the bug
I wrote my own little interface to connect the API of BedWars with the APIs on our server. When I cancel the BedwarsPlayerJoinEvent, I get a NullPointer. With this Exception I cant use this awesome plugin... Hope you guys can fix it soon! 

#### Server and plugin version
Spigot version: 1.16.1 (git-Paper-"0b33230f2"
BedWars version: tested it with 0.2.12 and the latest build on jenkins (0.2.13 Build 601)

#### Installed plugins on server (can be obtained by `/pl`)
over 40 (mostly our own plugins), but i can say it isn't a bug caused by them

#### Console log
```
[16:58:22 ERROR]: Could not pass event PlayerInteractEvent to BedWars v0.2.13-SNAPSHOT
java.lang.NullPointerException: null
        at org.screamingsandals.bedwars.game.GamePlayer.changeGame(GamePlayer.java:45) ~[?:?]
        at org.screamingsandals.bedwars.game.Game.joinToGame(Game.java:1261) ~[?:?]
        at org.screamingsandals.bedwars.utils.BedWarsSignOwner.onClick(BedWarsSignOwner.java:78) ~[?:?]
        at org.screamingsandals.bedwars.lib.signmanager.SignListener.onPlayerInteract(SignListener.java:34) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor181.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[spigot.jar:git-Paper-"0b33230f2"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[spigot.jar:git-Paper-"0b33230f2"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Paper-"0b33230f2"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[spigot.jar:git-Paper-"0b33230f2"]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1453) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[spigot.jar:git-Paper-"0b33230f2"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[spigot.jar:git-Paper-"0b33230f2"]
        at java.lang.Thread.run(Thread.java:835) [?:?]
```

#### Configuration (of config.yml and shop.yml)
config.yml 
```
locale: de
debug: false
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: false
join-randomly-after-lobby-timeout: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: true
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: false
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: false
damage-when-player-is-not-in-arena: true
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: false
player-respawn-items: false
gived-game-start-items: []
gived-player-respawn-items: []
disable-hunger: false
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion-except: ''
destroy-placed-blocks-by-explosion: true
holo-above-bed: false
allow-spectator-join: false
disable-server-message:
  player-join: false
  player-leave: false
disable-flight: false
respawn-cooldown:
  enabled: false
  time: 5
stop-team-spawners-on-die: false
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
farmBlocks:
  enable: false
  blocks: []
scoreboard:
  enable: true
  title: §a%game%§r - %time%
  bedLost: §c✘
  bedExists: §a✔
  teamTitle: '%bed%%color%%team%'
  anchorEmpty: §e✘
title:
  fadeIn: 0
  stay: 20
  fadeOut: 0
  enabled: true
shop:
  rows: 4
  render-actual-rows: 4
  render-offset: 0
  render-header-start: 0
  render-footer-start: 27
  items-on-row: 9
  show-page-numbers: true
  inventory-type: CHEST
  citizens-enabled: false
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: false
  reward:
    kill: 5
    win: 20
resources:
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Gold
    interval: 20
    translate: resource_gold
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: GRAY
    name: Iron
    interval: 10
    translate: resource_iron
    spread: 1.0
  bronze:
    material: BRICK
    color: DARK_RED
    name: Bronze
    interval: 1
    translate: resource_bronze
    spread: 1.0
respawn:
  protection-enabled: false
  protection-time: 10
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: false
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: true
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: CUT_SANDSTONE
  tnt-sheep:
    speed: 2.0
    follow-range: 10.0
    max-target-distance: 32
    explosion-time: 8
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 6
    delay: 0
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.25
    follow-range: 10
    health: 20
    name-format: '%teamcolor%%team% Golem'
    show-name: true
    delay: 0
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
  throwable-fireball:
    explosion: 3.0
  auto-igniteable-tnt:
    explosion-time: 8
    damage-placer: true
tnt:
  auto-ignite: false
  explosion-time: 8
  dont-damage-placer: false
sounds:
  on_bed_destroyed: ENTITY_ENDER_DRAGON_GROWL
  on_countdown: UI_BUTTON_CLICK
  on_game_start: ENTITY_PLAYER_LEVELUP
  on_team_kill: ENTITY_PLAYER_LEVELUP
  on_player_kill: ENTITY_PLAYER_BIG_FALL
  on_item_buy: ENTITY_ITEM_PICKUP
  on_upgrade_buy: ENTITY_EXPERIENCE_ORB_PICKUP
  on_respawn_cooldown_wait: UI_BUTTON_CLICK
  on_respawn_cooldown_done: ENTITY_PLAYER_LEVELUP
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: true
  title: §eBedWars
  content:
  - ' '
  - '§bArena: §7%arena%'
  - '§bSpieler: §7%players%§b/§7%maxplayers%'
  - ' '
  - '§bStatus: §eWarten'
  - ' '
statistics:
  enabled: true
  type: database
  show-on-game-end: true
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: <censored>
  port: <censored>
  db: <censored>
  user: <censored>
  password: <censored>
  table-prefix: bw_
  useSSL: false
bossbar:
  use-xp-bar: false
  lobby:
    enable: false
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: false
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: Deine §eBEDWARS§f-Statistiken
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  separate-chat:
    lobby: false
    game: false
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '@a'
  team-chat-prefix: '@t'
  all-chat: '[ALL] '
  team-chat: '[TEAM] '
  death-chat: '[DEATH] '
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
lore:
  generate-automatically: true
  text:
  - '§7Preis:'
  - §7%price% %resource%
  - '§7Anzahl:'
  - §7%amount%
sign:
  lines:
  - §c§l[BedWars]
  - §7%arena%
  - '%status%'
  - '%players%'
  block-behind:
    enabled: false
    waiting: ORANGE_STAINED_GLASS
    rebuilding: BROWN_STAINED_GLASS
    in-game: GREEN_STAINED_GLASS
    game-disabled: RED_STAINED_GLASS
hotbar:
  selector: 0
  color: 1
  start: 2
  leave: 8
breakable:
  enabled: false
  asblacklist: false
  blocks: []
leaveshortcuts:
  enabled: false
  list:
  - leave
mainlobby:
  enabled: false
  location: ''
  world: ''
turnOnExperimentalGroovyShop: false
preventSpectatorFlyingAway: true
removePurchaseMessages: false
disableCakeEating: true
disableDragonEggTeleport: true
preventArenaFromGriefing: false
version: 2
update-checker:
  zero:
    console: true
    admins: true
  one:
    console: true
    admins: true
target-block:
  respawn-anchor:
    fill-on-start: true
    enable-decrease: true
    sound:
      charge: BLOCK_RESPAWN_ANCHOR_CHARGE
      used: BLOCK_GLASS_BREAK
      deplete: BLOCK_RESPAWN_ANCHOR_DEPLETE
  allow-destroying-with-explosions: false
  cake:
    destroy-by-eating: true
event-hacks:
  damage: false
  destroy: false
  place: false
default-permissions:
  join: true
  leave: true
  stats: true
  list: true
  rejoin: true
  autojoin: true
```

shop.yml
```
data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Rüstung"
  row: 2
  column: 5
  items:
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_HELMET
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
     row: 2
     column: 0
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
     row: 2
     column: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
     row: 2
     column: 2
   - price: 1 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
     row: 2
     column: 3
   - price: 3 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
     row: 2
     column: 4
   - price: 7 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
     row: 2
     column: 5
   - price: 3 of iron
     stack:
      type: GOLDEN_BOOTS
      display-name: Schuhe
      enchants:
       PROTECTION_FALL: 3
     row: 2
     column: 6
       
- stack: "NETHERITE_SWORD;1;Waffen"
  row: 2
  column: 3
  items:
   - price: 8 of bronze
     stack:
      type: STICK
      enchants:
       KNOCKBACK: 1
     row: 2
     column: 0
   - price: 1 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 1
     row: 2
     column: 1
   - price: 3 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
     row: 2
     column: 2
   - price: 5 of gold
     stack:
      type: IRON_SWORD
      enchants:
       DAMAGE_ALL: 2
       KNOCKBACK: 1
     row: 2
     column: 3
   - price: 5 of iron
     stack:
      type: FISHING_ROD
     row: 2
     column: 4
   - price: 7 of iron
     stack:
      type: FLINT_AND_STEEL
      damage: 50
     row: 2
     column: 5
       
- stack: "BOW;1;Bögen"
  row: 3
  column: 5
  items:
   - price: 3 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
     row: 2
     column: 0
   - price: 7 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 1
     row: 2
     column: 1
   - price: 13 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 1
       ARROW_KNOCKBACK: 1
     row: 2
     column: 2
   - price: 1 of gold
     stack: ARROW
     row: 2
     column: 3

- stack: "COOKED_PORKCHOP;1;Essen"
  row: 2
  column: 6
  items:
   - price: 1 of bronze
     stack: APPLE
     row: 2
     column: 0
   - price: 4 of bronze
     stack:
      type: COOKED_PORKCHOP
      amount: 2
     row: 2
     column: 1
   - price: 2 of iron
     stack: GOLDEN_APPLE
     row: 2
     column: 2

- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "Tränke"
    potion-type: strength
  row: 3
  column: 3
  items:
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: healing
     price: 3 of iron
     row: 2
     column: 0
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strong_healing
     price: 5 of iron
     row: 2
     column: 1
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 7 of iron
     row: 2
     column: 2
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 7 of gold
     row: 2
     column: 3
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of gold
     row: 2
     column: 4

- stack: "SANDSTONE;1;Blöcke"
  row: 2
  column: 2
  items:
   - price: 1 of bronze
     stack:
      type: CUT_SANDSTONE
      amount: 2
     row: 2
     column: 0
   - price: 7 of bronze
     stack:
      type: END_STONE
      amount: 3
     row: 2
     column: 1
   - price: 3 of iron
     stack: IRON_BLOCK
     row: 2
     column: 2
   - price: 15 of bronze
     stack:
      type: GLOWSTONE
      amount: 2
     row: 2
     column: 3
   - price: 10 of bronze
     stack: COBWEB
     row: 2
     column: 4
   - price: 1 of bronze
     stack:
      type: CUT_SANDSTONE
      amount: 2
     row: 2
     column: 5
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: GLASS
     row: 2
     column: 6
   - price: 1 of iron
     stack: CHEST
     row: 2
     column: 7
   - price: 1 of gold
     stack: ENDER_CHEST
     row: 2
     column: 8
   - price: 1 of bronze
     stack: LADDER
     row: 2
     column: 9

- stack: "TNT;1;Besondere Items"
  row: 3
  column: 4
  items:
   - price: 2 of gold
     stack:
      type: TNT
     row: 2
     column: 0
   - price: 7 of iron
     properties:
      - name: "WarpPowder"
        delay: 6
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "Dieses Pulver teleportiert dich innerhalb"
       - "von 6 Sekunden zurück zu deiner Basis"
       - "§cAchtung: Jegliche Bewegungen würden den Vorgang abbrechen"
     row: 2
     column: 1
   - price: 3 of iron
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Falle"
      lore:
       - "Lässt deinen Gegner für 4 Sekunden erblinden"
       - "und verlangsamt diesen, während dein Team"
       - "eine Nachricht bekommt"
     row: 2
     column: 2
   - price: 12 of iron
     properties:
      - name: "MagnetShoes"
        probability: 75
     stack:
      type: IRON_BOOTS
      display-name: "Magnetschuhe"
      lore:
       - "Wenn du diese trägst, dann hat du"
       - "eine Chance von 75 % keinen Rückstoss zu erhalten"
     row: 2
     column: 3
   - price: 5 of iron
     properties: "Tracker"
     stack:
      type: COMPASS
      display-name: "Tracker"
     row: 2
     column: 4
   - price: 3 of gold
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rettungsplattform"
     row: 2
     column: 5
   - price: 13 of gold
     stack:
      type: ENDER_PEARL
     row: 2
     column: 6
   - price: 64 of bronze
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Sicherheitswall"
      lore:
       - "Erbaut sofort eine Wand,"
       - "welche dein Leben retten kann!"
     row: 2
     column: 7
   - price: 64 of bronze
     properties: "TNTSheep"
     stack:
      type: SHEEP_SPAWN_EGG
      display-name: "TNT Sheep"
      lore:
       - "Dieses besondere Schaf wird auf deinen"
       - "nähesten Gegner zulaufen und innerhalb"
       - "von 8 Sekunden explodieren!"
     row: 2
     column: 8
- stack: "DIAMOND_PICKAXE;1;Werkzeug"
  row: 2
  column: 4
  items:
   - price: 4 of bronze
     stack:
      type: WOODEN_PICKAXE
      enchants:
       DIG_SPEED: 1
     row: 2
     column: 0
   - price: 2 of iron
     stack:
      type: STONE_PICKAXE
      enchants:
       DIG_SPEED: 1
     row: 2
     column: 1
   - price: 1 of gold
     stack:
      type: IRON_PICKAXE
      enchants:
       DIG_SPEED: 3
     row: 2
     column: 2
```

#### Relevant code of the interface
```
    @EventHandler
    public void onJoins(BedwarsPlayerJoinEvent event) {
        Player player = event.getPlayer();
        if (player == null) return;

        String message = "<censored, but a nice little message :)>";

        if (<API-Call which returns if the player is allowed to join>) {
            event.setCancelMessage(message);
            event.setCancelled(true);
        }
    }
```
