### ISSUE TITLE
Jump boost V

### ISSUE THREAD

**Issue by SamSamsung** [ScreamingSandals/BedWars#244]
Hi, I think it would be a great idea to add jump boost potion V, like on Hypixel. That's all and merry Christmas !

**Comment by GGEZLOLLLLLLLLLLLLLLLLXD** [comment]
```yml
- stack:
      type: POTION
      display-name: "§aPotion of Leaping (Jump V for 60 seconds)" # Change name here
      meta:
        ==: ItemMeta
        meta-type: POTION
        potion-type: water
        custom-effects:
        - ==: PotionEffect
          effect: 8 # Effect ID, 8 is jump boost, 1 is speed
          duration: 1200 # Number of ticks the effect should last. 20 ticks => 1 second.
          amplifier: 4 # Amplifier of the potion effect. 0 => Level I, 4 => Level V
     price: <YOUR PRICE HERE>
```
