### ISSUE TITLE
Protection wall material not customizable 

### ISSUE THREAD

**Issue by FromenActual** [ScreamingSandals/BedWars#282]
#### Describe the bug
Changing the protection wall material in the config does not change the material in game; still creates wall out of cut sandstone. Is the material hard coded?

#### Server and plugin version
Spigot version: 1.16.5
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
BedWars, LuckPerms, PlaceholderAPI, Vault

#### Console log
N/A

#### Configuration (of config.yml and shop.yml)
```
specials:
  ...
  protection-wall:
    is-breakable: true
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: BRICKS
  tnt-sheep:
    ...
```

#### If there are problem with only one game, paste here config of this game
N/A

**Comment by iamceph** [comment]
Change it in your shop.yml.
Shop is thr main config and config.yml is used in case your shop is bad.

**Comment by FromenActual** [comment]
Ah, I wasn't aware the material was specified in the shop.yml since the default config doesn't include that. What's the syntax for changing the wall material? I tried adding a material to the properties section, but it's still cut sandstone.

```
- stack: "TNT;1;Utility;Useful items!"
  ...
  - stack: "BRICKS;1;Protection Wall;Creates a wall in front of you"
    price: 64 of bronze
    properties:
    - name: "protectionwall"
      material: BRICKS
  ...
```

Also, if my shop.yml is incorrect, shouldn't the material in config.yml fix it? I've specified it as bricks there.
