### ISSUE TITLE
block-behind block changes didn't take effect

### ISSUE THREAD

**Issue by Tobstr02** [ScreamingSandals/BedWars#289]
#### Describe the bug
If i set block-behind: enabled to true and change the block, like waiting to GREEN_CONCRETE, it doesn't apply after a reload of bedwars.
Also if i restart the server the change didn't take effect. No errors shown in console, also the yaml isn't resetting itself.

#### Server and plugin version
Spigot version: paper-1.16.5
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
Worldedit, Worldguard, Multiverse-Core, BedWars

#### Console log
No errors

#### Configuration (of config.yml and shop.yml)
```YAML
sign:
  lines:
  - §c§l[BedWars]
  - '%arena%'
  - '%status%'
  - '%players%'
  block-behind:
    enabled: true
    waiting: GREEN_CONCRETE
    rebuilding: BROWN_STAINED_GLASS
    in-game: BROWN_TERRACOTTA
    game-disabled: RED_TERRACOTTA
```
