### ISSUE TITLE
Identify cause of invalid configuration

### ISSUE THREAD

**Issue by PikaMug** [ScreamingSandals/BedWars#390]
#### Describe the solution you'd like

Attempting to purchase an upgrade on 0.2.21 results in this warning: https://github.com/ScreamingSandals/BedWars/blob/b6d3f8e8614f2ff8d3abf194fa5bea039bb22619/plugin/src/main/java/org/screamingsandals/bedwars/inventories/ShopInventory.java#L571

Please output a more descriptive warning so I can tell what's wrong.

#### Is your feature request related to a problem? Please describe

Here's the upgradeShop.yml I'm testing with (based on the snippet from https://docs.screamingsandals.org/BedWars/0.2.21/upgrades/):
```yaml
data:
- stack: "APPLE;1;Upgrades;Upgrade your stuff."
  row: 2
  column: 3
  items:
   - price: 1
     price-type: iron
     upgrade:
      entities:
       - type: spawner
      spawner-type: iron
      add-levels: 0.2
      shop-name: "iron upgrade of the team %team%"
      notify-team: true
     stack:
      type: DIAMOND_BLOCK
      amount: 1
      display-name: "iron upgrade of the team %team%"
```
