### ISSUE TITLE
TNT explosions not making damage on player

### ISSUE THREAD

**Issue by Sylensky** [ScreamingSandals/BedWars#397]
#### Describe the bug
On the latest version of bedwars the tnt sheep and the autoignited tnt aren't making damage to the player/enemy.

#### Server and plugin version
Spigot version: Paper version git-Paper-132 (MC: 1.18.1)
BedWars version: 0.2.22

#### Installed plugins on server (can be obtained by `/pl`)
![image](https://user-images.githubusercontent.com/57076968/147992998-617d3672-5303-473b-9aed-c020052740d8.png)

#### Console log
There are errors appearing in the console regarding bedwars.
#### Configuration (of config.yml and shop.yml)
[config.txt](https://github.com/ScreamingSandals/BedWars/files/7804609/config.txt)
[shop.txt](https://github.com/ScreamingSandals/BedWars/files/7804610/shop.txt)

**Comment by TheKouligkan** [comment]
Did you try to Allow {interact} in the area with WorldGuard?

**Comment by Sylensky** [comment]
Yes i have tried that flag. I also tried the {tnt}, {other-explosion} flags to no avail. The outcome is the same.

**Comment by zlataovce** [comment]
if you expect us to diagnose the issue, kindly provide the console log, `There are errors in the console regarding Bedwars` tells us nothing

**Comment by Sylensky** [comment]
here is the latest log. I freshly started the server and tried to kill a player with the autoignitable tnt and the tnt sheep.
Can you please point me to the error that bedwars throws?
[latest.log](https://github.com/ScreamingSandals/BedWars/files/7808018/latest.log)

**Comment by zlataovce** [comment]
I don't see any bedwars related errors in your log, try to replicate this on a server with no other plugin than bedwars (and multiverse if needed)

**Comment by swagbigpig** [comment]
Also try to unload CoreProtect maybe this plugin protects the players.

**Comment by Sylensky** [comment]
I have tested now with the following removed plugins:
- CoreProtect
- Multiverse-Core
- Multiverse-Inventories
- voidGen
- worldedit
- worldguard
Output was the same: TnT damage is not applied on enemy.
All the plugins are not affecting worlds.

**Comment by zlataovce** [comment]
can't reproduce on a **clean** server

**Comment by Caily-E** [comment]
It's cause your dynamicbungeeauth there are lines in the  config which cancels fall damage and explosions make it to false and then restart your server.

**Comment by Sylensky** [comment]
There are just these options on spigot side which i doubt are related to fall damage and explosions:
```
Options:
  # MaxTime = Once th player has reached the max time they will be kicked with a message (60 is recommended)
  MaxTime: 90
  # Disable the join messages of spigot
  DisableJoinMSG: false
  DisableLeaveMSG: false
  # BlindnessD = Set this to true to disable blindness on join
  BlindnessD: false
  # Enable AntiStuck if a server goes down and the player has been redirected to an AuthServer
  # The plugin will send the player if he is still a valid player "Logged in" to the Specified Server
  # Delay is on seconds recommended to be higher than 2
  AntiStuck:
    Enable: false
    Delay: 3
    Server: 'lobby'
  NameRegex: '^[a-zA-Z0-9_]*'
# Player options for when the player joins pre login or register.
PlayerOptions:
  BlockMovement: true
  BlockInteract: true
  BlockDrop: true
  BlockPickup: true
  BlockInventoryOpen: true
  BlockItemHeld: true

# Disable Weather and Rain on the Spigot Server.
WorldOptions:
  DisableRain: false
  DisableFood: false
```

**Comment by Caily-E** [comment]
Try to unload the plugin once and see if anything changes.

**Comment by Sylensky** [comment]
> can't reproduce on a **clean** server
Can you spare some details on the clean server you used for testing? like what server jar and which java version?

I just went through every plugin by disabling it and testing if there was a change. -sadly not.
![image](https://user-images.githubusercontent.com/57076968/148116675-b984c626-f4c0-4bde-89af-9f516d100b97.png)

I ended up with just the above green marked plugins which i am pretty sure they do nothing with worlds because plugman manages just the plugins that are installed.

Furthermore to be absolutely sure about that i think its a bedwars related issue i deleted all the plugins that arent required to run with bedwars and tested another time.
![image](https://user-images.githubusercontent.com/57076968/148117439-e370fe94-fc41-4013-bc79-f7d1f22f9b17.png)
Multiverse is required because its a different world where my arena is in.
And here the same outcome. - tnt doesnt do damage.

**Comment by zlataovce** [comment]
> Can you spare some details on the clean server you used for testing? like what server jar and which java version?
latest paper, java 17


do you have two arena positions overlapping by any chance?

**Comment by Sylensky** [comment]
I have these details on the arena with only one arena being created:
![image](https://user-images.githubusercontent.com/57076968/148119175-3b064570-d494-4a56-be15-f118a63a8396.png)

i followed the guide on the wiki with pos1 and pos2 markings. Did i miss a part there?

**Comment by zlataovce** [comment]
replicate the issue again and send the logs with debug set to true in the config

**Comment by Sylensky** [comment]
> here is the latest log. I freshly started the server and tried to kill a player with the autoignitable tnt and the tnt sheep. Can you please point me to the error that bedwars throws? [latest.log](https://github.com/ScreamingSandals/BedWars/files/7808018/latest.log)

Debug was set to true already at this log and the plugins didnt affect that behaviour before. 
Anyway here is the new log.
[latest.log](https://github.com/ScreamingSandals/BedWars/files/7810308/latest.log)

**Comment by notfoundname** [comment]
the reason why you can't take damage from autoigniteable TNT is `damage-placer: false` in shop

how does Autoigniteable TNT works:
when you place this special item, it removes that block immediately and spawns a modified TNT and if damage-placer is set to false, plugin adds a metadata to it with placer's UniqueID

plugin listens to EntityDamageByEntityEvent and checks if damaged player's UUID contains in TNT's metadata and if yes, plugin cancels damage to him, so everyone except placer gets damage from it.

TNTSheep just does not deal any damage to its activator and his teammates.

so if all TNT does not deal any damage to no one, and if it was bedwars' problem:
1. AutoigniteableTNT has metadata with all players' UUIDs (which is impossible, because only one player can place one block);
2. Everyone is in the same team (which is impossible too, when you start a game and everyone is your teammate, game starts and immediately ends)

**Comment by Sylensky** [comment]
I understand what you mean but i don't understand why it still happens.
```
  auto-igniteable-tnt:
    explosion-time: 8
    damage-placer: true
    damage: 4.0
```
The above settings were already set before creating the ticket.

**Comment by notfoundname** [comment]
these are default values, but you have specified custom values in shop

**Comment by Sylensky** [comment]
ah i found them and changed it for the tnt. but unfortunately there were no changes after testing.
```
- stack: "TNT;1;Useful Stuff;Looking for useful stuff?;Here are some!"
  column: center
  items:
   - CHEST for 1 of iron
   - ENDER_CHEST for 1 of gold
   - price: 3 of iron
     stack: "TNT;1;Autoigniteable TNT"
     properties:
      - name: "AutoIgniteableTnt"
        explosion-time: 5
        damage-placer: true
```

**Comment by notfoundname** [comment]
check your multiverse config

**Comment by Sylensky** [comment]
not sure what settings could interfere with bedwars here:
```
multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'true'
  prefixchatformat: '[%world%]%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'true'
  displaypermerrors: 'true'
  enablebuscript: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: Lobby
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'
  autopurge: 'true'
  idonotwanttodonate: 'false'
```

**Comment by notfoundname** [comment]
not that config, worlds config (I don't remember how it's called)

**Comment by Sylensky** [comment]
ah you mean this config:
```
worlds:
  arenas:
    ==: MVWorld
    hidden: 'false'
    alias: arenas
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: PEACEFUL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 65.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '7203088381919872763'
    generator: VoidGen
    playerLimit: '-1'
    allowFlight: 'true'
```
