### ISSUE TITLE
How to change the location of items in the store

### ISSUE THREAD

**Issue by RangeBanenge** [ScreamingSandals/BedWars#473]
Faced with the fact that I do not know how to change the location of items in the store HELP!

**Comment by FewerElk** [comment]
Try to change places in shop.yml

**Comment by RangeBanenge** [comment]
What do you mean? I want the store to be on the parameters of this: https://ru.files.fm/f/8zmvrwfwt 
there photo

**Comment by Misat11** [comment]
If you want to change the shop, please check this documentation of this format: https://github.com/ScreamingSandals/SimpleInventories/wiki (you are looking for pages listed under `variables`, other pages are irrelevant to you)
For example, you can move the item using variables like `row`, `column`, etc., but you can also omit these variables, so the items are next to each other.

As I have said in your other ticket, Github Issues are used for reporting bugs or requesting new features, but for general question and support Github Discussions or our Discord server should be used.

**Comment by RangeBanenge** [comment]
So I have to write a plugin based on the code from
https://github.com/ScreamingSandals/SimpleInventories/wiki#for-plugin-developers?


пт, 31 мар. 2023 г. в 20:39, Misat11 ***@***.***>:

**Comment by Misat11** [comment]
No, BedWars already have the code in it, you only need to modify the shop.yml, so check the section `For Server Owners` and ignore everything which says `For Plugin Developers`

**Comment by RangeBanenge** [comment]
Thanks a lot! I still got it!


сб, 1 апр. 2023 г. в 13:24, Misat11 ***@***.***>:

**Comment by RangeBanenge** [comment]
Sorry, just a few more questions. How do I get wool to be the color of
the team, like glass, and how do I adjust the timing of the potions?


сб, 1 апр. 2023 г. в 13:28, Максим Онищенко ***@***.***>:

**Comment by RangeBanenge** [comment]
Answer please...


сб, 1 апр. 2023 г. в 16:07, Максим Онищенко ***@***.***>:

**Comment by Misat11** [comment]
to color an item in the shop, you have to add this property to the item:
```yaml
properties: "applycolorbyteam"
```

to customize a potion, you have to use Bukkit's ItemMeta feature
```yaml
- stack:
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      custom-effects:
      - ==: PotionEffect
        effect: <effect type id>
        duration: <duration>
        amplifier: <amplifier>
        ambient: <true|false>
        has-particles: <true|false>
```

The format is described on this page: https://www.spigotmc.org/wiki/itemstack-serialization/ (scroll down to the section Potions and tipped arrows)
