### ISSUE TITLE
Fireworks

### ISSUE THREAD

**Issue by RangeBanenge** [ScreamingSandals/BedWars#496]
How to add fireworks with color to the store?

**Comment by Misat11** [comment]
According to https://www.spigotmc.org/wiki/itemstack-serialization/

```yaml
- stack:
    type: FIREWORK_ROCKET
    meta: 
      ==: ItemMeta
      meta-type: FIREWORK
      firework-effects:
      - ==: Firework
        flicker: <true|false>
        trail: <true|false>
        colors:
        - ==: Color
          RED: <red value>
          GREEN: <green value>
          BLUE: <blue value>
        - < .. more colors .. >
        fade-colors:
        - ==: Color
          RED: <red value>
          GREEN: <green value>
          BLUE: <blue value>
        - < .. more colors .. >
        type: <firework effect type name>
      - < .. more firework effects .. >
      power: <power>
```
