### ISSUE TITLE
Console Errors:  Cannot invoke "org.bukkit.Location.getWorld()" because "holoLocation" is null

### ISSUE THREAD

**Issue by petersvp** [ScreamingSandals/BedWars#497]
#### Describe the bug
`Cannot invoke "org.bukkit.Location.getWorld()" because "holoLocation" is null`

#### Server and plugin version
`[01:11:14] [Server thread/INFO]: This server is running CraftBukkit version 3836-Spigot-3374045-08ec344 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)`
BedWars-0.2.29

#### Installed plugins on server (can be obtained by `/pl`)
`[17:27:42] [Server thread/INFO]: Plugins (20): LuckPerms, VoidGen, WorldEdit, CommandHook, OpenInv, Sudo, Essentials, AntiNetherRoof, CXWCraft, Multiverse-Core, CXWAuth, WorldGuard, ProtocolLib, CoreProtect, WorldGuardExtraFlags, LibsDisguises, WorldEditSelectionVisualizer, SkinsRestorer, Orebfuscator, BedWars`
Issue happens with bedwars and mv alone

#### Console log
```
[17:10:25] [Server thread/WARN]: [BedWars] Task #12241 for BedWars v0.2.29 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "holoLocation" is null
        at org.screamingsandals.bedwars.holograms.StatisticsHolograms.updatePlayerHologram(StatisticsHolograms.java:139) ~[?:?]
        at org.screamingsandals.bedwars.holograms.StatisticsHolograms.lambda$updateHolograms$0(StatisticsHolograms.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3836-Spigot-3374045-08ec344]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3836-Spigot-3374045-08ec344]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3836-Spigot-3374045-08ec344]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3836-Spigot-3374045-08ec344]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3836-Spigot-3374045-08ec344]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3836-Spigot-3374045-08ec344]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3836-Spigot-3374045-08ec344]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

#### Configuration (of config.yml and shop.yml)
```
locale: en
debug: false
allow-crafting: false
keep-inventory-on-death: true
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: false
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: false
player-respawn-items: false
gived-game-start-items: []
gived-player-respawn-items: []
disable-hunger: false
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion-except:
- ''
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allow-spectator-join: false
disable-server-message:
  player-join: false
  player-leave: false
disable-flight: true
respawn-cooldown:
  enabled: true
  time: 5
stop-team-spawners-on-die: false
allow-fake-death: false
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
  motd:
    enabled: false
    waiting: '%name%: Waiting for players [%current%/%max%]'
    waiting_full: '%name%: Game is full [%current%/%max%]'
    running: '%name%: Game is running [%current%/%max%]'
    rebuilding: '%name%: Rebuilding...'
    disabled: '%name%: Game is disabled'
  kick-when-proxy-too-slow: true
farmBlocks:
  enable: false
  blocks: []
scoreboard:
  enable: true
  title: §a%game%§r - %time%
  bedLost: §c✘
  anchorEmpty: §e✘
  bedExists: §a✔
  teamTitle: '%bed%%color%%team%'
title:
  enabled: true
  fadeIn: 0
  stay: 20
  fadeOut: 0
shop:
  rows: 4
  render-actual-rows: 6
  render-offset: 9
  render-header-start: 0
  render-footer-start: 45
  items-on-row: 9
  show-page-numbers: true
  inventory-type: CHEST
  citizens-enabled: false
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: true
  reward:
    kill: 5
    win: 20
    final-kill: 5
    bed-destroy: 0
resources:
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Gold
    interval: 5
    translate: resource_gold
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: GRAY
    name: Iron
    interval: 1
    translate: resource_iron
    spread: 1.0
  diamond:
    material: DIAMOND
    color: AQUA
    name: Diamond
    interval: 30
    translate: resource_diamond
    spread: 1.0
  emerald:
    material: EMERALD
    color: GREEN
    name: Emerald
    interval: 40
    translate: resource_emerald
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 10
  show-messages: true
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: false
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: false
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: CUT_SANDSTONE
  tnt-sheep:
    speed: 0.25
    follow-range: 10.0
    max-target-distance: 32
    explosion-time: 8
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 6
    delay: 0
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.25
    follow-range: 10
    health: 20
    name-format: '%teamcolor%%team% Golem'
    show-name: true
    delay: 0
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
  throwable-fireball:
    explosion: 3.0
    damage: 3.0
    incendiary: true
    damage-thrower: true
  auto-igniteable-tnt:
    explosion-time: 8
    damage-placer: true
    damage: 4.0
  dont-show-success-messages: false
sounds:
  bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  my_bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  countdown:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  game_start:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  team_kill:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  player_kill:
    sound: ENTITY_PLAYER_BIG_FALL
    volume: 1
    pitch: 1
  item_buy:
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 1
  upgrade_buy:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1
    pitch: 1
  respawn_cooldown_wait:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  respawn_cooldown_done:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        ALPHA: 255
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: true
  title: §eBEDWARS
  content:
  - ' '
  - '§fMap: §2%arena%'
  - '§fPlayers: §2%players%§f/§2%maxplayers%'
  - ' '
  - §fWaiting ...
  - ' '
statistics:
  enabled: true
  type: yaml
  show-on-game-end: true
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
    final-kill: 0
database:
  host: localhost
  port: 3306
  db: database
  user: root
  password: secret
  table-prefix: bw_
  useSSL: false
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: Your §eBEDWARS§f stats
  leaderboard:
    headline: '&6Bedwars Leaderboard'
    format: '&l%order%. &7%name% - &a%score%'
    size: 10
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  separate-chat:
    lobby: false
    game: false
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '@a'
  team-chat-prefix: '@t'
  all-chat: '[ALL] '
  team-chat: '[TEAM] '
  death-chat: '[DEATH] '
  disable-all-chat-for-spectators: false
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
  player-win-run-immediately:
  - /example {player} 200
  player-final-kill:
  - /example {player} 10
lore:
  generate-automatically: true
  text:
  - '§7Price:'
  - §7%price% %resource%
  - '§7Amount:'
  - §7%amount%
sign:
  lines:
  - §c§l[BedWars]
  - '%arena%'
  - '%status%'
  - '%players%'
  block-behind:
    enabled: false
    waiting: ORANGE_STAINED_GLASS
    rebuilding: BROWN_STAINED_GLASS
    in-game: GREEN_STAINED_GLASS
    game-disabled: RED_STAINED_GLASS
hotbar:
  selector: 0
  color: 1
  start: 2
  leave: 8
breakable:
  enabled: false
  asblacklist: false
  blocks: []
leaveshortcuts:
  enabled: false
  list:
  - leave
mainlobby:
  enabled: false
  location: ''
  world: ''
turnOnExperimentalGroovyShop: false
preventSpectatorFlyingAway: false
removePurchaseMessages: false
disableCakeEating: true
disableDragonEggTeleport: true
preventArenaFromGriefing: false
update-checker:
  zero:
    console: true
    admins: true
  one:
    console: true
    admins: true
target-block:
  allow-destroying-with-explosions: false
  respawn-anchor:
    fill-on-start: true
    enable-decrease: true
    sound:
      charge: BLOCK_RESPAWN_ANCHOR_CHARGE
      used: BLOCK_GLASS_BREAK
      deplete: BLOCK_RESPAWN_ANCHOR_DEPLETE
  cake:
    destroy-by-eating: true
event-hacks:
  damage: false
  destroy: false
  place: false
tab:
  enable: false
  header:
    enabled: true
    contents:
    - '&aMy awesome BedWars server'
    - '&bMap: %map%'
    - '&cPlayers: %respawnable%/%max%'
  footer:
    enabled: true
    contents:
    - '&eexample.com'
    - '&fWow!!'
    - §a%spectators% are watching this match
  hide-spectators: true
  hide-foreign-players: false
default-permissions:
  join: true
  leave: true
  stats: true
  list: true
  rejoin: true
  autojoin: true
  leaderboard: true
  party: true
version: 2
enable-cheat-command-for-admins: false
shopkeepers-are-silent: true
prefer-1-19-4-display-entities: true
remember-what-scoreboards-players-had-before: false
kick-players-upon-final-death:
  enabled: false
  delay: 5
removePurchaseFailedMessages: false
removeUpgradeMessages: false
party:
  enabled: false
  autojoin-members: false
  notify-when-warped: true
```

```
data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Armor;Protect yourself with armor! Click here."
  items:
   - price: 1 of iron
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_HELMET
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of iron
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of iron
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of gold
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 3 of gold
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
   - price: 7 of gold
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
   - price: 10 of diamond
     stack:
      type: IRON_HELMET
      display-name: Helm
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
       
- stack: "DIAMOND_SWORD;1;Swords;Click here to get sword for attacking your enemies"
  column: center
  items:
   - price: 8 of gold
     stack:
      type: STICK
      enchants:
       KNOCKBACK: 1
   - price: 30 of iron
     stack:
      type: STONE_SWORD
      enchants:
       DAMAGE_ALL: 1
   - price: 10 of gold
     stack:
      type: IRON_SWORD
      enchants:
       DAMAGE_ALL: 2
   - price: 20 of gold
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 3
   - price: 3 of diamond
     stack:
      type: DIAMOND_SWORD
      enchants:
       DAMAGE_ALL: 2
       KNOCKBACK: 1
   - price: 4 of emerald
     stack:
      type: NETHERITE_SWORD
      enchants:
       DAMAGE_ALL: 10
       KNOCKBACK: 3
   - price: 15 of diamond
     stack:
      type: NETHERITE_AXE
      display-name: "Axe of Infinity"
      enchants:
       DAMAGE_ALL: 1
       DURABILITY: 1
       KNOCKBACK: 1
       
- stack: "BOW;1;Bows;Prove yourself as a marksman with these wonderful bows"
  column: right
  items:
   - price: 12 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
   - price: 40 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 1
   - price: 2 of diamond
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 2
   - price: 5 of diamond
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
   - price: 3 of emerald
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 1
   - ARROW;5 for 2 of gold

- stack: "COOKED_PORKCHOP;1;Eat;Are you hungry? Get something to eat."
  row: 3
  column: 2
  items:
   - COOKED_PORKCHOP;2 for 4 of iron
   - GOLDEN_APPLE for 3 of gold
   - price: 5 of emerald
     stack:
      type: ENCHANTED_GOLDEN_APPLE
      enchants:
       REGENERATION: 1
       FIRE_RESISTANCE: 1

   - BREAD;10 for 5 of diamond

- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "Drinks"
    lore:
     - "Not enough? Use these potions and you'll feel better!"
    potion-type: strength
  row: 3
  column: 6
  items:
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: healing
     price: 3 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strong_healing
     price: 5 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 7 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 1 of diamond
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of diamond

- stack: "WOOL;1;Blocks;Get to the others! Possible with blocks."
  linebreak: before
  items:
   - price: 4 of iron
     properties: "applycolorbyteam"
     stack: WOOL;16
   - END_STONE;3 for 7 of iron
   - IRON_BLOCK for 3 of gold
   - GLOWSTONE;4 for 15 of iron
   - price: 4 of iron
     properties: "applycolorbyteam"
     stack: GLASS
   - OBSIDIAN;8 for 3 of emerald


- stack: "TNT;1;Useful Stuff;Looking for useful stuff? Here are some!"
  column: center
  items:
   - CHEST for 1 of gold
   - ENDER_CHEST for 1 of diamond
   - price: 3 of gold
     stack: "TNT;1;Autoigniteable TNT"
     properties:
      - name: "AutoIgniteableTnt"
        explosion-time: 5
        damage-placer: false
   - price: 7 of gold
     properties:
      - name: "WarpPowder"
        delay: 6
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "When using this powder you'll get"
       - "teleported to you spawn point within 6 seconds"
       - "Warning: Any movement will stop the process"
   - price: 3 of gold
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to move properly."
   - price: 6 of gold
     properties:
      - name: "MagnetShoes"
        probability: 75
     stack:
      type: IRON_BOOTS
      display-name: "Magnet-Shoes"
      lore:
       - "Wear those shoes and have a 75%"
       - "chance of getting no knockback!"
   - price: 5 of gold
     properties: "Tracker"
     stack:
      type: COMPASS
      display-name: "Tracker"
      lore:
       - "Wanna know where your closest target is?"
       - "Let's try this out!"
   - price: 15 of gold
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rescue Platform"
      lore:
       - "Protect yourself from falling into"
       - "void with a Rescue Platform."
       - "This is your last hope!"
   - price: 5 of diamond
     properties:
      - name: "arrowblocker"
        delay: 5
     stack:
      type: ENDER_EYE
      display-name: "Arrow Blocker"
      lore:
       - "Block arrows that are coming"
       - "for you with black magic."
       - "I mean, with this item."
   - price: 64 of iron
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Protection Wall"
      lore:
       - "Instantly builds a wall that"
       - "can save your life!"
   - price: 24 of gold
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "An iron golem that will protect"
       - "your team from the enemies."
   - price: 10 of diamond
     properties: "TNTSheep"
     stack:
      type: SHEEP_SPAWN_EGG
      display-name: "TNT Sheep"
      lore:
       - "Use the TNT-Sheep! It will"
       - "walk towards your closest enemy"
       - "and explode within 8 seconds!"
   - price: 40 of iron
     properties: "ThrowableFireball"
     stack:
       type: FIRE_CHARGE
       display-name: "Fireball"
       lore:
         - "Is it a bird? Is it a plane?"
         - "By the time you know"
         - "you are dead!"

- stack: "DIAMOND_PICKAXE;1;Pickaxes;Destroy others blocks? Use these pickaxes."
  column: right
  items:
   - price: 4 of iron
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 1
   - price: 2 of gold
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 2
   - price: 1 of diamond
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 3
```
#### If there are problem with only one game, paste here config of this game
```
name: cxw
pauseCountdown: 10
gameTime: 900
world: BWCXW
pos1: 125.21966452269963;173.10844358697523;104.43657331656794;-181.08672;64.310135
pos2: -122.04168285473737;24.62273945625623;-128.86476349603407;-42.425232;-16.365927
specSpawn: 48.94470366505686;110.10144223165233;-2.7367383397214593;74.55087;30.811295
lobbySpawn: 0.4235303025771979;136.0;6.509883280166472;-0.051542968;9.992911
lobbySpawnWorld: BWCXW
minPlayers: 2
postGameWaiting: 3
teams:
  LemonGirl:
    isNewColor: true
    color: YELLOW
    maxPlayers: 2
    bed: 77.0;63.0;67.0;0.0;0.0
    spawn: 77.63108943339827;63.0625;80.04819698527609;183.38452;9.992191
  OceanEyes:
    isNewColor: true
    color: CYAN
    maxPlayers: 2
    bed: 1.0;63.0;89.0;0.0;0.0
    spawn: 1.490567319497716;63.0;99.61347740235422;180.98029;3.3192608
  Stuck:
    isNewColor: true
    color: RED
    maxPlayers: 2
    bed: -80.0;63.0;67.0;0.0;0.0
    spawn: -80.56731946945969;64.0;76.68884666991656;209.34189;-6.156383
  AutumnWeather:
    isNewColor: true
    color: BROWN
    maxPlayers: 2
    bed: -78.0;63.0;-65.0;0.0;0.0
    spawn: -78.43331026145705;63.0;-84.5947716966114;-34.15076;-1.2180051
  Homesick:
    isNewColor: true
    color: LIGHT_GRAY
    maxPlayers: 2
    bed: -5.0;63.0;-80.0;0.0;0.0
    spawn: -0.20986634636305668;63.0625;-96.15100254340314;4.8212404;-6.155754
  LilacSky:
    isNewColor: true
    color: MAGENTA
    maxPlayers: 2
    bed: 80.0;63.0;-67.0;0.0;0.0
    spawn: 80.7818080217452;64.0;-74.45115931856931;-337.4296;-6.0892406
spawners:
- maxSpawnedResources: -1
  hologramEnabled: false
  location: 79.43440852845026;63.5;-78.69999998807907;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: false
  location: 81.52396584334511;63.5;-78.50263538741586;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: false
  location: -1.4904855429216703;64.0;-101.52017483968703;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: false
  location: 0.446686479803584;64.0;-101.48196536936854;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: false
  location: -78.47495888190006;63.0;-89.46868364995827;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: false
  location: -76.50989859609096;63.0;-89.45722928213077;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: false
  location: -78.50666610196801;63.5;82.39731777984105;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: false
  location: -79.6017543262397;63.5;82.3564697276442;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: false
  location: 6.574750891116274;62.5;98.5400568628784;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: false
  location: 6.429765130961423;62.5;100.47114599467928;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: false
  location: 78.46423511093302;62.5;84.49009089516629;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: false
  location: 76.52578196201313;62.5;84.5108063606974;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 19.543613926103472;63.0;39.55626421636046;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: diamond
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -23.54839675460338;63.0;37.552687855175314;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: diamond
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -24.45623330626705;66.0;-34.3997589532151;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: diamond
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 32.00394987595142;62.0;-38.69999998807907;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: diamond
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 7.5454878199085265;64.0;-8.504562406673259;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: emerald
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -7.481274256628103;64.0;9.604726788947962;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: emerald
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 7.543067034279337;59.0;6.473025319876393;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: emerald
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -4.42970033100143;59.0;-6.42853014271929;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: emerald
stores:
- isBaby: 'false'
  loc: 89.30000001192093;64.0;-75.10507366990305;-284.6837;1.6514494
  parent: 'false'
  shop: null
  name: Tedro987
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: 86.69999998807907;63.0;79.00289159995411;-271.5141;0.9842019
  parent: 'false'
  shop: null
  name: PeterSvP
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: -8.300000011920933;63.0;-93.6852567075429;-86.23538;-1.9524015
  parent: 'false'
  shop: null
  name: Ynotxx
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: -86.32830439883365;63.0625;-80.20039248142727;-94.30475;8.524044
  parent: 'false'
  shop: null
  name: Fox Gamer_BG
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: -73.69999998807907;64.0;77.37413343527244;-274.92163;3.4538782
  parent: 'false'
  shop: null
  name: Christofer
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: -3.3000000119209285;63.0;99.91989584577288;-98.96631;7.5908303
  parent: 'false'
  shop: null
  name: Kosti01
  skin: null
  type: VILLAGER
constant:
  compass-enabled: inherit
  add-wool-to-inventory-on-join: inherit
  in-lobby-colored-leather-by-team: inherit
  allow-crafting: inherit
  join-randomly-after-lobby-timeout: inherit
  join-randomly-on-lobby-join: inherit
  keep-inventory-on-death: inherit
  prevent-killing-villagers: inherit
  player-drops: inherit
  friendlyfire: inherit
  lobbybossbar: inherit
  bossbar: inherit
  lobbyscoreboard: inherit
  scoreboard: inherit
  prevent-spawning-mobs: inherit
  spawner-holograms: inherit
  spawner-disable-merge: inherit
  game-start-items: inherit
  player-respawn-items: inherit
  spawner-holograms-countdown: inherit
  damage-when-player-is-not-in-arena: inherit
  remove-unused-target-blocks: inherit
  allow-block-falling: inherit
  holo-above-bed: inherit
  allow-spectator-join: inherit
  anchor-auto-fill: inherit
  anchor-decreasing: inherit
  cake-target-block-eating: inherit
  target-block-explosions: inherit
arenaTime: NOON
arenaWeather: CLEAR
lobbyBossBarColor: default
gameBossBarColor: default
```
