### ISSUE TITLE
Can't place blocks at certain Y-level

### ISSUE THREAD

**Issue by CCSNova** [ScreamingSandals/BedWars#505]
#### Describe the bug
Attempting to place blocks at -51 and above seems to not work at all

#### Server and plugin version
Purpur version:
![image](https://github.com/ScreamingSandals/BedWars/assets/100384210/90216e86-3a0a-4a41-9d09-edab43690645)
BedWars version:
0.2.29

#### Installed plugins on server (can be obtained by `/pl`)
![image](https://github.com/ScreamingSandals/BedWars/assets/100384210/9ccb3d5e-ff8c-43b4-902c-a367914171fd)

#### Console log
https://mclo.gs/tSalXyd

#### Configuration (of config.yml and shop.yml)
config.yml
```yaml
locale: ene
debug: false
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: false
join-randomly-after-lobby-timeout: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: true
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: true
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: true
player-respawn-items: true
gived-game-start-items:
- wooden_sword
- leather_helmet
- leather_boots
- leather_leggings
- leather_chestplate
gived-player-respawn-items:
- wooden_sword
- leather_helmet
- leather_boots
- leather_leggings
- leather_chestplate
disable-hunger: true
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
enable-cheat-command-for-admins: false
shopkeepers-are-silent: true
destroy-placed-blocks-by-explosion-except: []
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allow-spectator-join: false
disable-server-message:
  player-join: true
  player-leave: true
disable-flight: true
respawn-cooldown:
  enabled: true
  time: 5
stop-team-spawners-on-die: false
allow-fake-death: false
prefer-1-19-4-display-entities: true
remember-what-scoreboards-players-had-before: false
kick-players-upon-final-death:
  enabled: false
  delay: 5
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
  kick-when-proxy-too-slow: true
  motd:
    enabled: false
    waiting: '%name%: Waiting for players [%current%/%max%]'
    waiting_full: '%name%: Game is full [%current%/%max%]'
    running: '%name%: Game is running [%current%/%max%]'
    rebuilding: '%name%: Rebuilding...'
    disabled: '%name%: Game is disabled'
farmBlocks:
  enable: false
  blocks: []
scoreboard:
  enable: true
  title: '&a%game%&r - %time%'
  bedLost: '&c✘'
  anchorEmpty: '&e✘'
  bedExists: '&a✔'
  teamTitle: '%bed%%color%%team%'
title:
  enabled: true
  fadeIn: 0
  stay: 20
  fadeOut: 0
shop:
  rows: 4
  render-actual-rows: 6
  render-offset: 9
  render-header-start: 0
  render-footer-start: 45
  items-on-row: 9
  show-page-numbers: true
  inventory-type: CHEST
  citizens-enabled: true
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: false
  reward:
    kill: 5
    win: 20
    final-kill: 5
    bed-destroy: 0
resources:
  emerald:
    material: EMERALD
    color: GREEN
    name: Fancy Gem
    interval: 60
    translate: resource_emerald
    spread: 2.0
  diamond:
    material: DIAMOND
    color: BLUE
    name: Upgrade Gem
    interval: 30
    translate: resource_diamond
    spread: 1.0
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Advanced Gem
    interval: 7
    translate: resource_gold
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: WHITE
    name: Basic Gem
    interval: 2
    translate: resource_iron
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 10
  show-messages: true
specials:
  action-bar-messages: true
  dont-show-success-messages: false
  rescue-platform:
    is-breakable: false
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: false
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: CUT_SANDSTONE
  tnt-sheep:
    speed: 0.25
    follow-range: 10.0
    max-target-distance: 32
    explosion-time: 8
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 6
    delay: 0
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.25
    follow-range: 10
    health: 20
    name-format: '%teamcolor%%team% Golem'
    show-name: true
    delay: 0
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
  throwable-fireball:
    damage: 3.0
    incendiary: true
    damage-thrower: true
  auto-igniteable-tnt:
    explosion-time: 8
    damage-placer: true
    damage: 4.0
sounds:
  bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  my_bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  countdown:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  game_start:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  team_kill:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  player_kill:
    sound: ENTITY_PLAYER_BIG_FALL
    volume: 1
    pitch: 1
  item_buy:
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 1
  upgrade_buy:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1
    pitch: 1
  respawn_cooldown_wait:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  respawn_cooldown_done:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        ALPHA: 255
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: false
  title: '&eSculkWars'
  content:
  - ' '
  - '&fMap: &2%arena%'
  - '&fPlayers: &2%players%&f/&2%maxplayers%'
  - ' '
  - '&fWaiting ...'
  - ' '
statistics:
  enabled: true
  type: yaml
  show-on-game-end: false
  bed-destroyed-kills: false
  scores:
    kill: 10
    final-kill: 0
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: localhost
  port: 3306
  db: database
  user: root
  password: secret
  table-prefix: bw_
  useSSL: false
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: Your &eSculkwars&f stats
  leaderboard:
    headline: '&6Sculkwars Leaderboard'
    format: '&l%order%. &7%name% - &a%score%'
    size: 10
chat:
  override: false
  format: '<%teamcolor%%name%&r> '
  separate-chat:
    lobby: true
    game: true
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '@a'
  team-chat-prefix: '@t'
  all-chat: '[ALL] '
  team-chat: '[TEAM] '
  death-chat: '[DEATH] '
  disable-all-chat-for-spectators: false
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-win-run-immediately:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
  player-final-kill:
  - /example {player} 10
lore:
  generate-automatically: true
  text:
  - '&7Price:'
  - '&7%price% %resource%'
  - '&7Amount:'
  - '&7%amount%'
sign:
  lines:
  - '&c&l[SculkWars]'
  - '%arena%'
  - '%status%'
  - '%players%'
  block-behind:
    enabled: false
    waiting: ORANGE_STAINED_GLASS
    rebuilding: BROWN_STAINED_GLASS
    in-game: GREEN_STAINED_GLASS
    game-disabled: RED_STAINED_GLASS
hotbar:
  selector: 0
  color: 1
  start: 2
  leave: 8
breakable:
  enabled: false
  asblacklist: false
  blocks: []
leaveshortcuts:
  enabled: false
  list:
  - leave
mainlobby:
  enabled: true
  location: ''
  world: 'world'
turnOnExperimentalGroovyShop: true
preventSpectatorFlyingAway: false
removePurchaseMessages: false
removePurchaseFailedMessages: false
removeUpgradeMessages: false
disableCakeEating: true
disableDragonEggTeleport: true
preventArenaFromGriefing: false
update-checker:
  zero:
    console: true
    admins: true
  one:
    console: true
    admins: true
target-block:
  allow-destroying-with-explosions: false
  respawn-anchor:
    fill-on-start: true
    enable-decrease: true
    sound:
      charge: BLOCK_RESPAWN_ANCHOR_CHARGE
      used: BLOCK_GLASS_BREAK
      deplete: BLOCK_RESPAWN_ANCHOR_DEPLETE
  cake:
    destroy-by-eating: true
event-hacks:
  damage: false
  destroy: false
  place: false
tab:
  enable: false
  header:
    enabled: true
    contents:
    - '&aMy awesome BedWars server'
    - '&bMap: %map%'
    - '&cPlayers: %respawnable%/%max%'
  footer:
    enabled: true
    contents:
    - '&eexample.com'
    - '&fWow!!'
    - '&a%spectators% are watching this match'
  hide-spectators: true
  hide-foreign-players: false
default-permissions:
  join: true
  leave: true
  stats: true
  list: true
  rejoin: true
  autojoin: true
  leaderboard: true
  party: true
party:
  enabled: true
  autojoin-members: false
  notify-when-warped: true
version: 2
```

shop.yml
```yaml
#
# Copyright (C) 2023 ScreamingSandals
#
# This file is part of Screaming BedWars.
#
# Screaming BedWars is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Screaming BedWars is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Screaming BedWars. If not, see <https://www.gnu.org/licenses/>.
#

data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Armor;Protect yourself with armor! Click here."
  items:
   - price: 4 of iron
     stack:
      type: CHAINMAIL_BOOTS
      display-name: "Weak Boots"
   - price: 8 of iron
     stack:
      type: CHAINMAIL_LEGGINGS
      display-name: "Weak Leggings"
   - price: 6 of gold
     stack:
      type: IRON_BOOTS
      display-name: "Mechinal Boots"
   - price: 10 of gold
     stack:
      type: IRON_LEGGINGS
      display-name: "Mechinal Leggings"
   - price: 4 of emerald
     stack:
      type: DIAMOND_BOOTS
      display-name: "Powerful Boots"
   - price: 6 of emerald
     stack:
      type: DIAMOND_LEGGINGS
      display-name: "Powerful Leggings"
   - price: 8 of emerald
     stack:
      type: NETHERITE_BOOTS
      display-name: "Super Boots"
   - price: 14 of emerald
     stack:
      type: NETHERITE_LEGGINGS
      display-name: "Super Leggings"
       
- stack: "CACTUS;1;Poking Devices;Click here to get stuff for attacking your enemies"
  column: center
  items:
   - price: 32 of iron
     stack:
      type: STICK
      display-name: "Weak Punchy Poking Device"
      enchants:
       KNOCKBACK: 1
   - price: 16 of iron
     stack:
      type: STONE_SWORD
      display-name: "Advanced Poking Device"
   - price: 8 of iron
     stack:
      type: IRON_SWORD
      display-name: "Mechinal Poking Device"
   - price: 10 of emerald
     stack:
      type: DIAMOND_SWORD
      display-name: "Powerful Poking Device"
   - price: 25 of emerald
     stack:
      type: NETHERITE_SWORD
      display-name: "Super Poking Device"
      enchants:
       KNOCKBACK: 1
       
- stack: "BOW;1;Bows;Prove yourself as a marksman with these wonderful bows"
  column: right
  items:
   - price: 5 of gold
     stack:
      type: BOW
      display-name: "Standard Bow"
   - price: 10 of gold
     stack:
      type: BOW
      display-name: "Punchy Bow"
      enchants:
       ARROW_KNOCKBACK: 1
   - price: 13 of gold
     stack:
      type: BOW
      display-name: "Powerful Bow"
      enchants:
       ARROW_DAMAGE: 1
   - price: 20 of gold
     stack:
      type: BOW
      display-name: "Super Bow"
      enchants:
       ARROW_DAMAGE: 1
       ARROW_KNOCKBACK: 1
   - price: 2 of emerald
     stack:
      type: BOW
      display-name: "Firey Punch Bow"
      enchants:
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 1
   - price: 5 of emerald
     stack:
      type: BOW
      display-name: "Super Firey Punch Bow"
      enchants:
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 2
   - price: 10 of emerald
     stack:
      type: BOW
      display-name: "Super Powerful Firey Punch Bow"
      enchants:
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 2
       ARROW_DAMAGE: 1
   - price: 32 of emerald
     stack:
      type: BOW
      display-name: "Infinite God Bow"
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 2
       ARROW_DAMAGE: 1
   - ARROW;8 for 3 of gold

- stack:
    type: POTION
    display-name: "Drinks"
    lore:
      - "Not enough? Use these potions and you'll feel better!"
    potion-type: strength
  row: 3
  column: 6
  items:
    - stack:
        type: POTION
        potion-type: healing
      price: 3 of emerald
    - stack:
        type: POTION
        potion-type: strong_healing
      price: 5 of emerald
    - stack:
        type: POTION
        potion-type: swiftness
      price: 3 of emerald
    - stack:
        type: POTION
        potion-type: jump_boost
      price: 3 of emerald
    - stack:
        type: POTION
        potion-type: invisibility
      price: 7 of emerald

- stack: "WHITE_WOOL;1;Blocks;Get to the others! Possible with blocks."
  linebreak: before
  items:
   - price: 4 of iron
     properties: "applycolorbyteam"
     stack: "WOOL;16"
   - price: 16 of iron
     properties: "applycolorbyteam"
     stack: "TERRACOTTA;8"
   - OAK_PLANKS;4 for 4 of gold
   - END_STONE;4 for 32 of iron
   - LADDER;4 for 8 of iron
   - OBSIDIAN;4 for 2 of emerald

- stack: "GOLDEN_APPLE;1;Useful Stuff;Looking for useful stuff? Here are some!"
  column: center
  items:
   - CHEST for 10 of iron
   - ENDER_CHEST for 5 of gold
   - price: 3 of iron
     stack: "TNT;1;Autoigniteable TNT;Wow that's fast!"
     properties:
      - name: "AutoIgniteableTnt"
        explosion-time: 3
        damage-placer: false
   - price: 5 of emerald
     properties:
      - name: "WarpPowder"
        delay: 3
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "When using this powder you'll get"
       - "teleported to you spawn point within 3 seconds"
       - "Warning: Any movement will stop the process"
   - price: 32 of iron
     properties:
      - name: "MagnetShoes"
        probability: 25
     stack:
      type: IRON_BOOTS
      display-name: "Magnet-Shoes"
      lore:
       - "Wear those shoes and have a 25%"
       - "chance of getting no knockback!"
   - price: 2 of emerald
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rescue Platform"
      lore:
       - "Protect yourself from falling into"
       - "void with a Rescue Platform."
       - "This is your last hope!"
   - price: 3 of emerald
     properties:
      - name: "arrowblocker"
        delay: 5
     stack:
      type: ENDER_EYE
      display-name: "Arrow Blocker"
      lore:
       - "Block arrows that are coming"
       - "for you with black magic."
       - "I mean, with this item."
   - price: 64 of iron
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Protection Wall"
      lore:
       - "Instantly builds a wall that"
       - "can save your life!"
   - price: 120 of iron
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "An iron golem that will protect"
       - "your team from the enemies."
   - price: 15 of gold
     properties: "TNTSheep"
     stack:
      type: SHEEP_SPAWN_EGG
      display-name: "TNT Sheep"
      lore:
       - "Use the TNT-Sheep! It will"
       - "walk towards your closest enemy"
       - "and explode within 8 seconds!"
   - price: 10 of gold
     properties: "ThrowableFireball"
     stack:
       type: FIRE_CHARGE
       display-name: "Fireball"
       lore:
         - "Is it a bird? Is it a plane?"
         - "By the time you know"
         - "you are dead!"

- stack: "DIAMOND;1;Team Upgrades;Get upgrades for the squad!"
  column: right
  items:
  - price: 1 of diamond
    properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 3
            duration: 30
            ambient: true
            has-particles: true
            has-icon: true
    stack:
      type: STRING
      display-name: "Slowness Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to move properly."
  - price: 1 of diamond
    properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 30
            ambient: true
            has-particles: true
            has-icon: true
    stack:
      type: STRING
      display-name: "Blindness Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to see."
  - price: 2 of diamond
    properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 4
            amplifier: 2
            duration: 60
            ambient: true
            has-particles: true
            has-icon: true
    stack:
      type: STRING
      display-name: "Weak Hands Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to mine very well."
  - price: 3 of diamond
    properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 20
            amplifier: 1
            duration: 10
            ambient: true
            has-particles: true
            has-icon: true
    stack:
      type: STRING
      display-name: "Smart Clear Wither Rose™"
      lore:
       - "Gives the enemy wither when stepped on"
       - "and you'll be informed about it!"
  - price: 2
    price-type: diamond
    upgrade:
      entities:
      - type: spawner
      spawner-type: iron
      add-levels: 0.1
      max-level: 1.5
      shop-name: "Upgrades the iron generator for your team"
      notify-team: true
    stack:
      type: IRON_BLOCK
      amount: 1
      display-name: "Upgrades the iron generator for your team"
  - price: 5
    price-type: diamond
    upgrade:
      entities:
      - type: spawner
        spawner-type: gold
        add-levels: 0.05
        max-level: 1.25
        shop-name: "Upgrades the gold generator for your team"
        notify-team: true
    stack:
      type: DIAMOND_BLOCK
      amount: 1
      display-name: "Upgrades the gold generator for your team"

- stack: "DIAMOND_PICKAXE;1;Tools;Destroy others blocks? Use these tools."
  column: right
  items:
   - price: 15 of iron
     stack:
      type: WOODEN_PICKAXE
      display-name: "Weak Pickaxe"
   - price: 10 of gold
     stack:
      type: IRON_PICKAXE
      display-name: "Mechinal Pickaxe"
   - price: 5 of emerald
     stack:
      type: DIAMOND_PICKAXE
      display-name: "Powerful Pickaxe"
   - price: 10 of emerald
     stack:
      type: NETHERITE_PICKAXE
      display-name: "Super Pickaxe"
   - price: 15 of iron
     stack:
      type: WOODEN_AXE
      display-name: "Weak Axe"
   - price: 10 of gold
     stack:
      type: IRON_AXE
      display-name: "Mechinal Axe"
   - price: 5 of emerald
     stack:
      type: DIAMOND_AXE
      display-name: "Powerful Axe"
   - price: 10 of emerald
     stack:
      type: NETHERITE_AXE
      display-name: "Super Axe"
```
