### ISSUE TITLE
[Bug]: It everytime says Your shop.yml/shop.groovy is wrong! Loading default one instead but i cant find anything

### ISSUE THREAD

**Issue by EnverAdam** [ScreamingSandals/BedWars#529]
### Bug description

It says "[BedWars] Your shop.yml/shop.groovy is wrong! Loading default one instead". I cant find any error, i edited the script and removed some parts.

### BedWars dump (can be obtained via `/bw dump`)

It says failed

### Console log

https://mclo.gs/gLxKFpM

### Additional information

My shop:
```
data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Armor;Protect yourself with armor! Click here."
  items:
   - price: 1 of iron
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_HELMET
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of iron
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of iron
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of diamond
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 3 of diamond
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
   - price: 7 of diamond
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
   - price: 10 of emerald
     stack:
      type: IRON_HELMET
      display-name: Helm
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
       
- stack: "DIAMOND_SWORD;1;Kılıçlar;Düşmana karşı saldırı!"
  column: center
  items:
   - price: 15 of iron
     stack:
      type: STONE_SWORD
      
   - price: 3 of diamond
     stack:
      type: IRON_SWORD
      
   - price: 7 of emerald
     stack:
      type: DIAMOND_SWORD
      
   - price: 6 of diamond
     stack:
      type: STICK
      enchants:
       KNOCKBACK: 2
       
- stack: "BOW;1;Yaylar;LEGOLASMI BU A"
  column: right
  items:
   - price: 64 of iron
     stack:
      type: BOW
      enchants:
   - price: 7 of diamond
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 1
   - price: 5 of emerald
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 2
   - price: 12 of emerald
     stack:
      type: BOW
      enchants:
      ARROW_KNOCKBACK: 1
      ARROW_DAMAGE: 2
   - price: 17 of emerald
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_KNOCKBACK: 1
       ARROW_DAMAGE: 2
   - ARROW;2 for 1 of diamond
- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "İksirler"
    lore:
     - "Yetmedimi? İksir var iksir iç"
    potion-type: strength
  row: 3
  column: 6
  items:
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: healing
     price: 3 of diamond
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strong_healing
     price: 5 of diamond
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 7 of diamond
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 1 of emerald
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of emerald

- stack: "SANDSTONE;1;Bloklar;Değişik şeyler"
  linebreak: before
  items:
   - CUT_SANDSTONE;2 for 1 of iron
   - END_STONE;3 for 7 of iron
   - IRON_BLOCK for 3 of diamond
   - GLOWSTONE;4 for 15 of iron
   - price: 4 of iron
     properties: "applycolorbyteam"
     stack: GLASS

- stack: "TNT;1;Değişik Şeyler;Değişik"
  column: center
  items:
   - CHEST for 1 of diamond
   - price: 3 of diamond
     stack: "TNT;1;Autoigniteable TNT"
     properties:
      - name: "TNT"
        explosion-time: 5
        damage-placer: false
   - price: 5 of emerald
     properties:
      - name: "WarpPowder"
        delay: 6
     stack:
      type: GUNPOWDER
      display-name: "Spawn Tozu"
      lore:
       - "Kullandığında seni 6 saniye içinde spawnına ışınlar"
       - "Uyarı: Haraket edersen ışınlanma iptal olur"
   - price: 3 of diamond
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Tuzak"
      lore:
       - "Tuzak kur"
   - price: 64 of iron
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Koruma Duvarı"
      lore:
       - "Kullanıldığında önünde duvar belirir"
   - price: 48 of iron
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "golem işte"
   - price: 40 of diamond
     properties: "ThrowableFireball"
     stack:
       type: FIRE_CHARGE
       display-name: "Ateş Topu"
       lore:
         - "Gördüğün şey kuşmu uçak mı?"
         - "Daha bilemediğin anda"
         - "Öldün!"
- stack: "DIAMOND_PICKAXE;1;Kazma;Blok kaz"
  column: right
  items:
   - price: 12 of iron
     stack:
      type: WOOD_PICKAXE
   - price: 8 of diamond
     stack:
      type: IRON_PICKAXE
   - price: 3 of emerald
     stack:
      type: DIAMOND_PICKAXE
```
